/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import java.awt.Color;
import java.awt.Cursor;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.Timer;


/**
 *
 * @author E.B.A.X. Company
 */
   
public class Sign_in extends javax.swing.JFrame{
   
    /**
     * Creates new form Sign_in2
     */
    public Sign_in() {
        this.setResizable(false);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfnickname = new javax.swing.JTextField();
        pfpassword = new javax.swing.JPasswordField();
        lbbSignUp = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblinvalidpass = new javax.swing.JLabel();
        lblinvalidnick = new javax.swing.JLabel();
        exit = new javax.swing.JLabel();
        lbbSignIn = new javax.swing.JLabel();
        lbRegisteration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("I CAR");
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(49, 117, 236));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel2MouseReleased(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_car_sale_100px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("I C A R");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 2, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("The limit of imagination and reality...");
        jLabel7.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel7)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tfnickname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfnickname.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(49, 117, 236)));
        jPanel3.add(tfnickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 168, 34));

        pfpassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pfpassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(49, 117, 236)));
        jPanel3.add(pfpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 170, 30));

        lbbSignUp.setBackground(new java.awt.Color(255, 255, 255));
        lbbSignUp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbbSignUp.setForeground(new java.awt.Color(49, 117, 236));
        lbbSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbSignUp.setText("Sign up");
        lbbSignUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 117, 236), 1, true));
        lbbSignUp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbbSignUp.setOpaque(true);
        lbbSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbSignUpMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbSignUpMouseExited(evt);
            }
        });
        jPanel3.add(lbbSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 90, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-user-20 (1).png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8-lock-20 (1).png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 20, 30));

        lblinvalidpass.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lblinvalidpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 240, 20));

        lblinvalidnick.setForeground(new java.awt.Color(255, 0, 0));
        jPanel3.add(lblinvalidnick, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 180, 20));

        exit.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_delete_20px.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });
        jPanel3.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 30, 40));

        lbbSignIn.setBackground(new java.awt.Color(255, 255, 255));
        lbbSignIn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbbSignIn.setForeground(new java.awt.Color(49, 117, 236));
        lbbSignIn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbbSignIn.setText("Sign In");
        lbbSignIn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(49, 117, 236), 1, true));
        lbbSignIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbbSignIn.setOpaque(true);
        lbbSignIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbbSignInMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbbSignInMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbbSignInMouseExited(evt);
            }
        });
        jPanel3.add(lbbSignIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 40));

        lbRegisteration.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbRegisteration.setForeground(new java.awt.Color(153, 204, 0));
        lbRegisteration.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(lbRegisteration, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 240, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbbSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignUpMouseClicked
       
        
        if(tfnickname.getText().isEmpty()){
            lblinvalidnick.setText("*Invalid nickname!");
        }
        if(!tfnickname.getText().isEmpty()){
            lblinvalidnick.setText("");
        }
        if(String.valueOf(pfpassword.getPassword()).length()<=5){
           lblinvalidpass.setText("*Password length 6 or higher recommended!");
       
        }
        if(String.valueOf(pfpassword.getPassword()).length()>5){
            lblinvalidpass.setText("");
        } 
        if(!tfnickname.getText().isEmpty() && String.valueOf(pfpassword.getPassword()).length()>5){
            
            try {
                nickWriteFile(tfnickname.getText());
            } catch (IOException ex) {
                Logger.getLogger(Sign_in.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                passWriteFile(pfpassword.getPassword());
            } catch (IOException ex) {
                Logger.getLogger(Sign_in.class.getName()).log(Level.SEVERE, null, ex);
            }
            
             
            lbRegisteration.setText("Registeration Completed!"); 
            lbRegisteration.setForeground(Color.blue);
        }
       
        
        
        
       
        
    }//GEN-LAST:event_lbbSignUpMouseClicked
int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        xx = evt.getX();
        xy = evt.getY();
        this.setCursor(Cursor.MOVE_CURSOR);
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
        this.setCursor(Cursor.MOVE_CURSOR);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void jPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseReleased
        this.setCursor(Cursor.DEFAULT_CURSOR);
    }//GEN-LAST:event_jPanel2MouseReleased

    private void lbbSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignUpMouseEntered
        setColor(lbbSignUp);
    }//GEN-LAST:event_lbbSignUpMouseEntered

    private void lbbSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignUpMouseExited
        resetColor(lbbSignUp);
    }//GEN-LAST:event_lbbSignUpMouseExited

    private void lbbSignInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignInMouseClicked
        try {
            if(isPasswordCorrect(pfpassword.getPassword(),(Integer)nickFinder(tfnickname.getText()))){
                this.setVisible(false);
                new Home().setVisible(true);
            }
            else{
                lbRegisteration.setText("Nickname/password incorrect!");
                lbRegisteration.setForeground(Color.red);
                tfnickname.setText("");
                pfpassword.setText("");
            }
        } catch (IOException ex) {
            Logger.getLogger(Sign_in.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lbbSignInMouseClicked

    private void lbbSignInMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignInMouseEntered
        setColor(lbbSignIn);
    }//GEN-LAST:event_lbbSignInMouseEntered

    private void lbbSignInMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbbSignInMouseExited
        resetColor(lbbSignIn);
    }//GEN-LAST:event_lbbSignInMouseExited
    
    public void setColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(197, 197, 197));
 }
 
 public void resetColor(JLabel panel)
 {
     panel.setBackground(new java.awt.Color(255,255,255));
 }
 
 
   public void nickWriteFile(String element)throws IOException{
        try (FileWriter nickWriter = new FileWriter("nicknames.txt",true)) {
            nickWriter.write(element+"\n");
        }
   }
   public void passWriteFile(char[] element)throws IOException{
        try (FileWriter passwordWriter = new FileWriter("passwordss.txt",true)) {
            passwordWriter.write(element);
            passwordWriter.write("\n");
           
        }
   
   }
   
   public Object nickFinder(String element) throws FileNotFoundException, IOException{
        BufferedReader br = new BufferedReader(new FileReader("nicknames.txt"));
        int index=0;
        String line=null;      
        while( (line=br.readLine()) != null) {
                if(element.equals(line)){
                    return index;
                }
                index++;
            }   
        return null;
   }
   
    public boolean isPasswordCorrect(char[] element,Integer index) throws FileNotFoundException, IOException {
        BufferedReader br = new BufferedReader(new FileReader("passwordss.txt"));
        int passline=0;
        String line=null;      
        try{
        while((line=br.readLine()) != null) {
                if(passline==index && Arrays.equals(line.toCharArray(), element)){
                    return true;
                    
                }
                passline++;
            }
        
        return false;
        }catch (NullPointerException n){
           return false;
                
        }}
       
    
    public static void main(String args[])  {
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sign_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sign_in().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbRegisteration;
    private javax.swing.JLabel lbbSignIn;
    private javax.swing.JLabel lbbSignUp;
    private javax.swing.JLabel lblinvalidnick;
    private javax.swing.JLabel lblinvalidpass;
    private javax.swing.JPasswordField pfpassword;
    private javax.swing.JTextField tfnickname;
    // End of variables declaration//GEN-END:variables
}
